repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.11
    hooks:
      - id: ruff
        args: [--target-version=py37, --fix]
      - id: ruff-format
        args: [--target-version=py37]
